before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/generate/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: cagenerator
    id: "cagenerator"
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w

# Добавляем специальную конфигурацию для go install
nfpms:
  - id: cagenerator
    package_name: cagenerator
    file_name_template: "{{ .ProjectName }}"
    builds:
      - cagenerator

gomod:
  proxy: true
  mod: mod
  gobinary: go

# Указываем Go модуль для установки
project_name: cagenerator

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:' 